# Generated by Django 4.1.1 on 2024-09-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_created_at_alter_account_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmeter',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
