# Generated by Django 4.1.1 on 2024-07-20 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('accounts', '0002_alter_account_created_at_alter_account_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.PositiveIntegerField(unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('meter_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.accountmeter')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='token_payment', to='payments.payment')),
            ],
        ),
        migrations.CreateModel(
            name='ElectrictyBalanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(null=True)),
                ('current_usage', models.FloatField(null=True)),
                ('voltage_usage', models.FloatField(null=True)),
                ('timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('meter_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.accountmeter')),
            ],
        ),
        migrations.CreateModel(
            name='ElectricityBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(default=0, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('meter_no', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meter_balance', to='accounts.accountmeter')),
            ],
        ),
    ]
