# Generated by Django 4.1.1 on 2024-07-20 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_order_key'),
        ('accounts', '0002_alter_account_created_at_alter_account_updated_at_and_more'),
        ('balances', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tokens',
            new_name='Token',
        ),
    ]
