# Generated by Django 4.1.1 on 2024-09-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balances', '0002_rename_tokens_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electrictybalancelog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
