# Generated by Django 5.1.1 on 2024-10-01 22:05

import balances.model_utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_accountmeter_location'),
        ('balances', '0004_electrictybalancelog_apparent_power'),
    ]

    operations = [
        migrations.CreateModel(
            name='LightSwitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_usage', models.FloatField(null=True)),
                ('voltage_usage', models.FloatField(default=balances.model_utils.generate_random_voltage, null=True)),
                ('apparent_power', models.FloatField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('meter_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.accountmeter')),
            ],
        ),
        migrations.CreateModel(
            name='SocketSwitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_usage', models.FloatField(null=True)),
                ('voltage_usage', models.FloatField(default=balances.model_utils.generate_random_voltage, null=True)),
                ('apparent_power', models.FloatField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('meter_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.accountmeter')),
            ],
        ),
    ]
