# Generated by Django 5.1.1 on 2024-10-08 04:07

import balances.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balances', '0005_lightswitch_socketswitch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.PositiveBigIntegerField(default=balances.models.create_new_ref_number, unique=True),
        ),
    ]
