# Generated by Django 4.1.1 on 2024-07-20 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order_key',
            field=models.CharField(default='b6346288949c408b8940c9e175b77f', max_length=200),
        ),
    ]
