# Generated by Django 4.1.1 on 2024-09-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_order_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order_key',
            field=models.CharField(default='938f77c796264a60901cf843f9f251', max_length=200),
        ),
    ]
