# Generated by Django 5.1.1 on 2024-09-10 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_order_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order_key',
            field=models.CharField(default='3e5e7f512d104b5a81d2827d2baf92', max_length=200),
        ),
    ]
