# Generated by Django 5.1.1 on 2024-09-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_payment_order_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order_key',
            field=models.CharField(default='cb354767a2b544beaca4d89b61d153', max_length=200),
        ),
    ]
