# Generated by Django 5.1.1 on 2024-10-01 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_payment_order_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order_key',
            field=models.CharField(default='0c2e3cba45274d6e97d4cb6d19db64', max_length=200),
        ),
    ]
