# Generated by Django 5.1.1 on 2024-10-08 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_alter_payment_order_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order_key',
            field=models.CharField(default='30772e4d1b7543fa8b9ef3242a015c', max_length=200),
        ),
    ]
