# Generated by Django 5.1.1 on 2024-10-07 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_alter_payment_order_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order_key',
            field=models.CharField(default='27ebddec81b44e8aa6b4f60d5bd64d', max_length=200),
        ),
    ]
