# Generated by Django 5.1.1 on 2024-10-07 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_alter_payment_order_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order_key',
            field=models.CharField(default='e16a7198a96d4e37b1ce9bf27b6cce', max_length=200),
        ),
    ]
