# Generated by Django 3.2.25 on 2024-10-07 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_alter_payment_order_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order_key',
            field=models.CharField(default='d106339f780b4fac9b60ef4be724ab', max_length=200),
        ),
    ]
